# Generated by Django 5.2 on 2025-04-27 20:13

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='corretores', variations={}, verbose_name='Foto'),
        ),
    ]
