# Generated by Django 5.2 on 2025-04-27 22:46

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=50, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('tipo_transacao', models.CharField(choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel')], max_length=10)),
                ('valor_iptu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos_imovel', variations={})),
                ('descricao', models.TextField(blank=True)),
                ('quartos', models.PositiveIntegerField()),
                ('banheiros', models.PositiveIntegerField()),
                ('vagas_garagem', models.PositiveIntegerField()),
                ('tipo_imovel', models.CharField(choices=[('APTO', 'Apartamento'), ('CASA', 'Casa'), ('COBERT', 'Cobertura'), ('DUPLEX', 'Duplex'), ('KITNET', 'Kitnet'), ('LOJA', 'Loja'), ('PAVIL', 'Pavilhão'), ('COMERCIAL', 'Comercial')], max_length=10)),
                ('status_imovel', models.CharField(choices=[('NOVO', 'Novo'), ('USADO', 'Usado'), ('PLANTA', 'Planta'), ('CONSTR', 'Em construção')], max_length=10)),
                ('tem_condominio', models.BooleanField(default=False)),
                ('tem_financiamento', models.BooleanField(default=False)),
                ('tem_mobilia', models.BooleanField(default=False)),
                ('tem_churrasqueira', models.BooleanField(default=False)),
                ('tem_elevador', models.BooleanField(default=False)),
                ('tem_lareira', models.BooleanField(default=False)),
                ('tem_piscina', models.BooleanField(default=False)),
                ('tem_portaria_24h', models.BooleanField(default=False)),
                ('tem_sacada', models.BooleanField(default=False)),
                ('tem_salao_festa', models.BooleanField(default=False)),
            ],
        ),
    ]
