# Generated by Django 5.2 on 2025-04-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente', max_length=100, verbose_name='Nome')),
                ('celular', models.CharField(help_text='Celular completo do cliente', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Email completo do cliente', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
