# Generated by Django 5.2 on 2025-04-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do proprietário', max_length=100, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Celular completo do proprietário', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Email completo do proprietário', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
            },
        ),
    ]
